name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.operating_system }}-latest
    strategy:
      matrix:
        operating_system: [ ubuntu ]
        ruby_version: [ '2.6', '2.7', '3.0', '3.1', '3.2', '3.3' ]
        include:
          - { operating_system: macos, ruby_version: '3.2' }
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - run: bundle exec rake
